[tools]
"aqua:atuinsh/atuin" = "latest"
yazi = "latest"
fzf = "latest"
zoxide = "latest"
fd = "latest"
ripgrep = "latest"
bat = "latest"
eza = "latest"
usage = "latest"
viddy = "latest"
dust = "latest"
helix = "latest"
starship = "latest"
jj = "latest"
gh = "latest"
uv = "latest"
delta = "latest"
direnv = "latest"

[env]
AZCOPY_AUTO_LOGIN_TYPE = "AZCLI"
AZURE_CORE_COLLECT_TELEMETRY = 0
JUPYTER_PLATFORM_DIRS = 1
